apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: cat-managed-cert
spec:
  domains:
    - cat.npsolve.com
---
apiVersion: v1
kind: Service
metadata:
  name: katzemeo-np
spec:
  selector:
    app: katzemeo
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: katzemeo-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
#    kubernetes.io/ingress.global-static-ip-name: my-static-address
    kubernetes.io/ingress.allow-http: "false"
    networking.gke.io/managed-certificates: cat-managed-cert
    networking.gke.io/v1beta1.FrontendConfig: "http-to-https"
spec:
  defaultBackend:
    service:
      name: katzemeo-np
      port:
        number: 80
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: http-to-https
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT